(function () {
  window.NRC_CONFIG = {
    title: 'Neon Rift Courier',
    version: '1.0.0',
    worldRadius: 2400,
    basePlayerSpeed: 310,
    playerAccel: 1600,
    dashSpeed: 940,
    dashDuration: 0.16,
    dashCooldown: 1.15,
    basePlayerHp: 100,
    baseFireRate: 0.22,
    baseDamage: 12,
    baseShardValue: 10,
    waveDuration: 52,
    bossWave: 12,
    sectorUpgradeEvery: 3,
    maxEnemies: 46,
    maxPickups: 20,
    maxParticles: 700,
    storageKey: 'nrc_save_v1',
    audioKey: 'nrc_audio_enabled_v1',
    cameraLag: 0.12,
    shakeDamp: 14,
    starCount: 240,
    autoAimRange: 820,
    orbOrbitRadius: 34,
    comboDecay: 0.85,
    sparksPerWave: 4,
  };
})();
